# OSS Audit — Open Source Audit Project

**Student Name:** Prashil Dhingani 
**Chosen Software:** Git  
**Course:** Open Source Software  
**Project:** The Open Source Audit — Capstone Project (Units 1–5)

---

## 📁 Repository Structure

```
oss-audit-[24BCE10368]/
│
├── Script1.sh        # System Identity Report
├── Script2.sh        # FOSS Package Inspector
├── Script3.sh        # Disk and Permission Auditor
├── Script4.sh        # Log File Analyzer
├── Script5.sh        # Open Source Manifesto Generator
└── README.md         # This file
```

---

## 📜 Script Descriptions

### Script 1 — System Identity Report
Displays a welcome-style system identity report including the Linux distribution name, kernel version, current logged-in user, home directory, system uptime, current date and time, and the open-source license that covers the OS (GPL).

**Concepts used:** Variables, `echo`, command substitution `$()`, `uname`, `whoami`, `uptime`, `date`, `if-else`, `/etc/os-release` parsing.

---

### Script 2 — FOSS Package Inspector
Checks whether the chosen software (`git`) is installed on the system. If installed, it displays version information. A `case` statement then prints a short philosophy note about the package based on its name.

**Concepts used:** `if-then-else`, `case` statement, `dpkg -l`, `grep`, pipe `|`.

---

### Script 3 — Disk and Permission Auditor
Loops through a list of important system directories (`/etc`, `/var/log`, `/home`, `/usr/bin`, `/tmp`) and reports the permissions, owner, and disk usage of each. Also checks if Git's configuration directory exists and prints its permissions.

**Concepts used:** `for` loop, arrays, `ls -ld`, `du -sh`, `awk`, `cut`, `if` condition.

---

### Script 4 — Log File Analyzer
Reads a log file line by line and counts how many lines contain a specified keyword (default: `error`). Prints a summary count and displays the last 5 matching lines.

**Concepts used:** `while read` loop, `if-then`, counter variables, command-line arguments (`$1`, `$2`), `grep`, `tail`.

---

### Script 5 — Open Source Manifesto Generator
Interactively asks the user three questions and composes a personalised open-source philosophy statement using their answers. The manifesto is saved to a `.txt` file named after the current user.

**Concepts used:** `read` for user input, string concatenation, writing to a file with `>` and `>>`, `date` command, alias concept demonstrated via comment.

---

## ⚙️ How to Run Each Script on Linux

> **Prerequisites:** A Linux system (Ubuntu/Debian recommended). Git must be installed for Script 2 to detect it.  
> Make all scripts executable before running:
> ```bash
> chmod +x Script1.sh Script2.sh Script3.sh Script4.sh Script5.sh
> ```

---

### ▶️ Script 1
```bash
./Script1.sh
```
No arguments needed. Just run it and it will display your system identity report.

---

### ▶️ Script 2
```bash
./Script2.sh
```
No arguments needed. It automatically checks for `git` and prints the philosophy note.

---

### ▶️ Script 3
```bash
./Script3.sh
```
No arguments needed. It will audit the default directories and check for Git config.

---

### ▶️ Script 4
```bash
./Script4.sh /var/log/syslog error
```
- **Argument 1:** Path to the log file (e.g. `/var/log/syslog`)
- **Argument 2:** Keyword to search for (default is `error` if not provided)

Example with default keyword:
```bash
./Script4.sh /var/log/syslog
```

---

### ▶️ Script 5
```bash
./Script5.sh
```
No arguments needed. The script will prompt you with 3 questions interactively. Your manifesto will be saved as `manifesto_<username>.txt` in the current directory.

---

## 🔧 Dependencies

| Script | Dependencies |
|--------|-------------|
| Script 1 | `bash`, `uname`, `whoami`, `uptime`, `date` — all pre-installed on Linux |
| Script 2 | `bash`, `dpkg`, `git` |
| Script 3 | `bash`, `ls`, `du`, `awk`, `cut` — all pre-installed on Linux |
| Script 4 | `bash`, `grep`, `tail` — all pre-installed on Linux |
| Script 5 | `bash`, `date` — all pre-installed on Linux |

> All scripts are written for **Ubuntu/Debian** Linux systems. Script 2 uses `dpkg` for package checking.

---

## 📝 Notes
- All scripts include inline comments explaining each section.
- Scripts must be run on a real Linux system or virtual machine.
- Script 4 requires a valid, non-empty log file as input.
- The manifesto generated by Script 5 is saved in the same directory where the script is run.
